#Persisted Channels storage file  by EFI Analytics, Inc
#Last Saved on: Thu Jun 05 17:34:17 MDT 2025
#Thu Jun 05 17:34:17 MDT 2025
_(\ (\ tsInputSpeedMPH\ *\ 1.60934\ )\ /\ 3600.0\ *\ deltatime\ )=0.0
_(\ tsInputSpeedMPH\ /\ 3600.0\ *\ deltatime\ )=0.0
